### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by cakekyst** [mattmiller87/RLScrape#6]
'utf-8' codec can't decode byte 0xae in position 17: invalid start byte

Assuming it just couldn't read this person: Criscoo®#2952

**Comment by mattmiller87** [comment]
https://github.com/mattmiller87/RLScrape/blob/a90ab9f0c2b8de456f98ed3aeb34b6b591ec3124/asynccsv.py#L38

need to look into changing encoding='utf-8' to encoding="ISO-8859-1" I feel like this solved it last time and I went back to utf-8

**Comment by mattmiller87** [comment]
updated to `encoding="ISO-8859-1` in https://github.com/mattmiller87/RLScrape/tree/test - needs actually tested

**Comment by mattmiller87** [comment]
I believe this may work, and be a bit better for future proofing across different OS - `with open(self.csvinput, 'rb' newline ='') as csvread:`

Python 3 defaults to encoding UTF-8 everywhere.  Looks like windows uses Latin-1 (ISO-8859-1) to read text.

**Comment by mattmiller87** [comment]
^ that didn't work.  tests showed encoding="latin-1" is the solution for win10. osx did not care either way.  so `latin-1` is probably the best choice.
